image: node:18.16.0

stages:
  - install
  - test
  - build
  - deploy

install:
  stage: install
  script:
    - npm install
  artifacts:
    expire_in: 1h
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

tests:
  stage: test
  variables:
    CHROME_BIN: google-chrome
  dependencies:
    - install
  before_script:
    - apt-get update && apt-get install -y apt-transport-https
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update && apt-get install -y google-chrome-stable
  script:
    - npm run test:ci
  coverage: '/Statements.*?(\d+(?:\.\d+)?)%/'
build:
  stage: build
  dependencies:
    - install
  script:
    - npm run build
  artifacts:
    expire_in: 1h
    paths:
      - dist/
  only:
    - master
firebase:
  stage: deploy
  dependencies:
    - build
  before_script:
    - npm install -g firebase-tools@12.3.1
    - npm install --save-dev @angular-devkit/build-angular
  script:
    - firebase use tema17ej2 --token 1//03WkbEZbiaQdcCgYIARAAGAMSNwF-L9IrrvalNo20lvZNG4Jtttml0fPL41-NuX_u9GmvHtcIuw_6G3SEAkSm1SNA1dirAZj3tI0
    - firebase experiments:enable webframeworks
    - firebase deploy --token 1//03WkbEZbiaQdcCgYIARAAGAMSNwF-L9IrrvalNo20lvZNG4Jtttml0fPL41-NuX_u9GmvHtcIuw_6G3SEAkSm1SNA1dirAZj3tI0
  only:
    - master
